name: singleton_example
version: 1.0.0
homepage: https://github.com/timnew/singleton.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.2.3
  async: ^2.4.2
  singleton:

dev_dependencies:
  test: ^1.15.4

dependency_overrides:
  singleton:
    path: ../
