name: singleton
description: Singleton make singleton implementation less hassle, and also make it more friendly to tests.
version: 0.0.2
homepage: https://github.com/timnew/singleton.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.2.3
  async: ^2.4.2

dev_dependencies:
  test: ^1.15.4
