name: singleton
description: Singleton without hassle
version: 0.0.1
homepage: https://github.com/timnew/singleton.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  async: ^2.4.2

dev_dependencies:
  test: ^1.15.4